Kv = function() {
    this.stressedVowelTranslations = {
        "a": "a",
        "ä": "e",
        "e": "ej",
        "i": "ij",
        "y": "y",
        "o": "o",
        "ou": "ooo",
        "u": "ł",
        "ü": "u",
        "ea": "aaa",
        "ear": "aaa",
        "ei": "eee",
        "eir": "eee"
        "ae": "iii",
        "ö": "er",
        "ör": "er",
        "eo": "uuu",
        "eu": "au",
        "ey": "aj",
        "ui": "oj",
    };

    this.unstressedVowelTranslations = {
        "a": "a",
        "ä": "e",
        "e": "ł",
        "er": "ł",
        "i": "ij",
        "y": "y",
        "o": "o",
        "ou": "ooo",
        "u": "ł",
        "ü": "u",
        "ea": "aaa",
        "ear": "aaa",
        "ei": "eee",
        "eir": "eee"
        "ae": "iii",
        "ö": "er",
        "ör": "er",
        "eo": "uuu",
        "eu": "au",
        "ey": "aj",
        "ui": "oj",
    };


    this.consonantsAdjacentConsonants = {
        "m": "m",
        "mm": "m",
        "n": "n",
        "nn": "n",
        "ng": "ng",
        "p": "p",
        "pp": "p",
        "t": "t",
        "tt": "t",
        "th": "t",
        "k": "k",
        "kk": "k",
        "ck": "k",
        "b": "b",
        "bb": "b",
        "d": "d",
        "dd": "d",
        "dt": "d",
        "g": "g",
        "gh": "g",
        "f": "f",
        "ff": "f",
        "s": "s",
        "h": "h",
        "sch": "sz",
        "ch": "ś",
        "z": "z",
        "zsch": "ż",
        "rzsch": "rz",
        "rzch": "rz",
        "rsch": "rz",
        "v": "w",
        "w": "w",
        "l": "l",
        "ll": "l",
        "j": "j",
        "r": "r"
    };

    this.consonantsAdjacentVowels = {
        "m": "m",
        "mm": "m",
        "n": "n",
        "nn": "n",
        "ng": "ng",
        "p": "p",
        "pp": "p",
        "t": "t",
        "tt": "t",
        "th": "t",
        "k": "k",
        "kk": "k",
        "ck": "k",
        "b": "b",
        "bb": "b",
        "d": "d",
        "dd": "d",
        "dt": "d",
        "g": "g",
        "gh": "g",
        "f": "f",
        "ff": "f",
        "ſ": "s",
        "ſs": "s",
        "h": "h",
        "sch": "sz",
        "ch": "ś",
        "z": "c",
        "s": "z",
        "zsch": "ż",
        "rzsch": "rz",
        "rzch": "rz",
        "rsch": "rz",
        "v": "w",
        "w": "w",
        "l": "l",
        "ll": "l",
        "j": "j",
        "r": "r"
    };

    this.speak = function(text) {
        // TODO
    };
};

kv = new Kv();
